[package]
name = "tcping"
version = "1.0.1"
authors = ["lvillis<lvillis@outlook.com>"]
edition = "2021"
description = "A tool for testing native-to-target port latency, using Rust."
license = "MIT"
repository = "https://github.com/lvillis/tcping-rs"
homepage = "https://github.com/lvillis/tcping-rs"
documentation = "https://github.com/lvillis/tcping-rs/README.md"

[workspace]
members = [".", "bin/ref-type"]

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
ctrlc = "3.4.5"
